# list of meta tags
- name: keywords
  content: > 
    Webifier, Sharif University of Technology, Mohammad Hossein Rohban, Markov Decision Processes,
    Supplementary Material, Additional Content, Deep Learning, Machine Learning, Artificial Intelligence, Probability and Statistics, 
- name: author
  content: sut-ai